version: '3.7'

services:

  # service to start django server
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    image: thumbnail_generator
    volumes:
      - .:/thumbnail_generator
    env_file:
      - .env.docker
    ports:
      - 8000:8000
  
  # service to start celery worker
  celery:
    build: .
    command: celery -A thumbnail_generator worker
    image: thumbnail_generator
    volumes:
      - .:/thumbnail_generator
    env_file:
      - .env.docker
    depends_on:
      - redis

  # service to start redis
  redis:
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  # service to run test cases
  test:
    build: .
    command: bash -c "python manage.py test"
    image: thumbnail_generator
    volumes:
      - .:/thumbnail_generator
    env_file:
      - .env.docker
    depends_on:
      - web
      - celery
      - redis
