version: '3.7'

services:

  # service to start django server
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    image: thumbnail_generator
    volumes:
      - .:/thumbnail_generator
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
  # service to start celery worker
  celery:
    build: .
    command: celery -A thumbnail_generator worker
    image: thumbnail_generator
    volumes:
      - .:/thumbnail_generator
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
  
  # service to start postgres database
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=postgresDb

  # service to start redis
  redis:
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

volumes:
  postgres_data: